# Generated by Django 5.0.6 on 2024-06-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
            ],
            options={
                'verbose_name': 'coffee',
                'verbose_name_plural': 'coffees',
            },
        ),
    ]
